run:
  name: archive
  description: Start files archiving
  fields:
    instance: 
      name: instance name
      description: Instance name in config->camera_archiver->entities->name
      example: 'Yi1080pWoodSouth'
      default: 'Yi1080pWoodSouth'
      required: true
    component:
      name: component to run
      description: component type in config->camera_archiver->entities->from->name (or platform)
      example: 'ftp'
      default: 'ftp'
      required: true
      selector:
        select:
          options:
            - "ftp"
            - "directory"
            - "mqtt"
    direction:
      name: from or to
      description: component type in config->camera_archiver->entities->from (or to)
      example: 'from'
      default: 'from'
      required: true
      selector:
        select:
          options:
            - "from"
            - "to"

