run:
  name: run archiving
  description: Start files archiving
  fields:
    component: 
      name: serice type component
      description: id of component with type 'service' in camera_archiver config
      example: 'service_run'
      default: 'service_run'
      required: true
